version: '3.3'

services:
  app:
    build: .
    ports:
      - "8002:8000"
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL_NAME=text-embedding-3-small
      - DEFAULT_CHUNK_SIZE=1000
      - DEFAULT_CHUNK_OVERLAP=200
      - DEFAULT_SEARCH_RESULTS=5
      - DEFAULT_SIMILARITY_THRESHOLD=0.5
    depends_on:
      - chroma

  chroma:
    image: chromadb/chroma:latest
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - ALLOW_RESET=true
      - ANONYMIZED_TELEMETRY=false
    ports:
      - "8001:8000"

volumes:
  chroma_data:
    driver: local